### ISSUE TITLE
Trouble using XDF files 

### ISSUE THREAD

**Issue by 2020Supra** [dmacpro91/BMW-XDFs#10]
Good day. Thanks for posting these files! I have 10 years of HP tuner experience on GM cars but Tuner Pro is new to me and driving me crazy. I have DL the proper bins that you posted for the MKV Supra and they work properly with other BMW XDF files that I DL from the Tuner pro site, but for the life of me I can't get the associated Supra XDF files to properly upload to Tuner Pro. No matter how I DL it or using 3 different browsers I always get the following error. "error parser does not support utf-8 language encodings"

Do you have any idea what I'm doing wrong?

Thanks in advance. Any help is appreciated.

**Comment by jyamona** [comment]
Hi,

You need to download the whole repo as a zip file and then extract the XDFs
you need.

**Comment by 2020Supra** [comment]
Jake, 

Thanks! Spent the last 24 hours going crazy trying to figure it out and it was just that easy. Any chance you have any youtube vids or internet posts doing b58 gen 2 tuning? Seems like most of the tuners understandably keep this info pretty tight.
