### ISSUE TITLE
Using Kess

### ISSUE THREAD

**Issue by Pho3niX90** [dmacpro91/BMW-XDFs#2]
Does these XDF's work with Kess?

**Comment by PanagiotouGrigorios** [comment]
Hello sorry for typing here it is the only way , to ask for help. My name is Gregory Panagiotou i am from Greece , i drive a Bmw E90 320i with the N46 inline 4 engine with 6 speed manual transmission , recently i change my differential to a shorter ratio from 3,38 to 3,64 my problem is that the cruise control is not working , i saw that you resolve the problem for the 335 owners by modifying the gear table and the differential ratio table on the dme , please sent me an email with more  information about the modification of the original software in the ecu . My email address is grpanagi@uth.gr  also my facebook profile is https://www.facebook.com/profile.php?id=100000776464863 .
